'use strict';
function FM430() {
  console.log("FM430: Constructor run")
  this.hid = null;
  this.packageQueue = [];
  this.deviceBusy = false;
  this.resultsRetriever_resultCallback = null;
  this.resultsRetriever_errorCallback = null;
  this.resultsRetriever_type = null;
}

FM430.prototype.constructor = FM430;

require('./fm430-main')(FM430);
require('./fm430-autogenerated')(FM430);

module.exports = FM430;